### ISSUE TITLE
Usage with xBrowserSync

### ISSUE THREAD

**Issue by luxoboy** [gaoqing/history-as-bookmark#1]
Hello,

I found your work in the search for a sync solution between instances which would include history.
As history sync is not yet implemented in xBrowserSync, I looked for a solution to manage history as bookmarks.

I tested the combination of your work and xBrowserSync and it was not successful.

I thought I'd let you know in case you'd be interested in the scenario (syncing history across instances) and want to investigate.

Cheers,
Anthony.

**Comment by luxoboy** [comment]
Details on « it was not successful » : 
- one sync action included the "history as bookmarks" folder
- later history items were not synced

**Comment by gaoqing** [comment]
Thanks for raising, I just have a quick read xBrowserSync website, it seems they will somehow read user's browser bookmarks and send them remotely over to a network storage(3rd party/private remote store). 
My extension just simply but programmatically  add your browsing history into bookmark items under this folder named `___EXTENSION_HISTORY_AS_BOOKMARKS_FOLDER___`  (you can find this folder in bookmark manager).  there is no blocker for xBrowserSync to read them same way as reading other bookmark folder(if they want).

Probably you need to raise to xBrowserSync team why their tool fail to read a very normal folder,  or xBrowserSync need  specific user action(eg. user manually click to add as bookmark) as a trigger point for its tool to pick new bookmark up.  Ask them if they can pick up bookmarks that were added programmatically like my extension.
